all: spawn.txt

# Purpose: Clears the old README.md and generates the new README.md markdown file
spawn.txt:
	echo '' > README.md

	echo '# Davidius Number Guessing Game' >> README.md
	echo '\n##### (Author) David Hsu' >> README.md
	echo '##### (Course) The Unix Workbench: Peer-graded Assignment: Bash, Make, Git, and GitHub' >> README.md

	echo '\n---' >> README.md

	echo '\n[ Execution Time and Date ]\' >> README.md
	echo $(shell date) >> README.md

	echo '\n[ Number of Lines of Code in "guessinggame.sh" ]\' >> README.md
	echo $(shell cat guessinggame.sh | wc -l) >> README.md

	echo '\n[ GitHub Pages Site URL generated by README.md ]\' >> README.md
	echo '[https://davidiuswesker.github.io/davidius-number-guessing-game-git-repot/](https://davidiuswesker.github.io/davidius-number-guessing-game-git-repot/)' >> README.md

# Purpose: Manually delete the README.md markdown file
clean:
	rm README.md